config/routes.rb
Rails.application.routes.draw do
  devise_for :clients
  root 'welcome#home'
  resources :dogs
  resources :clients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/dog.rb
class Dog < ApplicationRecord
  validates :name, presence: true
  mount_uploader :avatar, DogAvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def index
    @clients = Client.all
  end

  def show
    load_client
  end

  def create
    client = Client.new(client_params)
    if client.save
      message =  {success: 'Your client was created'}
    else
      message =  {success: client.errors.full_messages.to_sentence}
    end
    redirect_to new_client_path, flash: message
  end

  def update
    load_client
    @client.update(client_params)
    redirect_to edit_client_path(@client), flash: {success: 'Your client was updated'}
  end

  def destroy
    load_client
    @client.destroy
    redirect_to clients_path, flash: {success: 'Your client was deleted'}
  end

  def edit
    load_client
  end

  private

  def client_params
    params.require(:client).permit(:name, :age, :email)
  end

  def load_client
    @client = Client.find(params[:id])
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def new
    @dog = Dog.new
  end

  def index
    @dogs = Dog.all
  end

  def show
    load_dog
  end

  def create
    dog = Dog.new(dog_params)
    if dog.save
      message =  {success: 'Your dog was created'}
    else
      message =  {success: dog.errors.full_messages.to_sentence}
    end
    redirect_to new_dog_path, flash: message
  end

  def update
    load_dog
    @dog.update(dog_params)
    redirect_to edit_dog_path(@dog), flash: {success: 'Your dog was updated'}
  end

  def destroy
    load_dog
    @dog.destroy
    redirect_to dogs_path, flash: {success: 'Your dog was deleted'}
  end

  def edit
    load_dog
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :breed, :avatar)
  end

  def load_dog
    @dog = Dog.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, class: 'form-group' do |form| %>
  Name:<%= form.text_field :name, class: 'form-control col-12' %><br />
  Age: <%= form.text_field :age, class: 'form-control  col-12' %><br />
  Email: <%= form.text_field :email, class: 'form-control  col-12' %><br />
  <div class="text-center">
    <%= form.submit nil , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<div class="w-25">
  <h1>Update <%= @client.name %></h1>
  <%= render 'form' %>
</div>

app/views/clients/index.html.erb
<div class="w-100 text-center h-100 p-4">
  <h1>List of Clients</h1>

  <div class="dogs-index d-flex flex-wrap ml-5 overflow-auto">
    <table class="table mt-5">
      <thead class="thead-dark">
        <tr>
          <th>N</th>
          <th>Name</th>
          <th>Age</th>
          <th>Email</th>
          <th colspan="2">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each_with_index do |client, idx| %>
          <tr>
            <td><%= idx + 1 %></td>
            <td><%= client.name.capitalize %></td>
            <td><%= client.age %></td>
            <td><%= client.email %></td>
            <td><%= link_to 'Update', edit_client_path(client), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Delete', client_path(client), method: :delete, class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/clients/new.html.erb
<div class="w-25">
  <h1>Create a new Client</h1>
  <%= render 'form' %>
</div>

app/views/clients/show.html.erb
<h1>Client#Show</h1>
Name: <%= @client.name%>
Age: <%= @client.age%>
Email: <%= @client.email%>

app/views/dogs/_form.html.erb
<%= form_for @dog, class: 'form-group' do |form| %>
  Name:<%= form.text_field :name, class: 'form-control col-12' %><br />
  Age: <%= form.text_field :age, class: 'form-control  col-12' %><br />
  Breed: <%= form.text_field :breed, class: 'form-control  col-12' %><br />
  Picture: <%= form.file_field :avatar %>
  <div class="text-center">
    <%= form.submit nil , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<div class="w-25">
  <h1>Update <%= @dog.name %></h1>
  <%= render 'form' %>
</div>

app/views/dogs/index.html.erb
<div class="w-100 text-center h-100 p-4">
  <h1>You can adopt them!</h1>

  <div class="dogs-index d-flex flex-wrap ml-5 overflow-auto">
    <% @dogs.each do |dog| %>
    <div class="card d-inline-flex w-25 m-5">
      <div class="card-body">
        <div class="card-title">
          <%= image_tag(dog.avatar.url.to_s, class: 'w-100') %>
          <%= dog.name.capitalize %>
        </div>
        <div class="">
          <p>
            Age: <%= dog.age %>
          </p>
          <p>
            Breed: <%= dog.breed.capitalize %>
          </p>
        </div>
        <%= link_to 'Update', edit_dog_path(dog), class: 'btn btn-primary' %>
        <%= link_to 'Delete', dog_path(dog), method: :delete, class: 'btn btn-danger' %>
      </div>

    </div>
    <% end %>
  </div>

</div>

app/views/dogs/new.html.erb
<div class="w-25">
  <h1>Create a new Dog</h1>
  <%= render 'form' %>
</div>

app/views/dogs/show.html.erb
<h1>Dog#Show</h1>
Name: <%= @dog.name%>
Age: <%= @dog.age%>
Breed: <%= @dog.breed%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShelterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash %>
      <% flash.each do |type, msg| %>
        <div class="success"><%= msg %></div>
      <% end %>
    <% end %>

    <div class="sidebar shadow-lg p-3 mb-5 bg-white rounded">
      <div class="w-100 text-center">
        <%= link_to root_path do %>
          <img src="https://static.thenounproject.com/png/52856-200.png" alt="" width="70">
        <% end %>
      </div>
      <div class=" w-100">
        <h3>Dogs</h3>

        <%= link_to new_dog_path  do %>
          <div class="pl-5 mt-3 border-bottom">
            <p>
              Create a dog
            </p>
          </div>
        <% end %>

        <%= link_to dogs_path  do %>
          <div class="pl-5 mt-3 border-bottom">
            <p>
              See all the dogs
            </p>
          </div>
        <% end %>

      </div>
      <div class="w-100">
        <h3>Clients</h3>

        <%= link_to new_client_path  do %>
          <div class="pl-5 mt-3 border-bottom">
            <p>
              Create a client
            </p>
          </div>
        <% end %>

        <%= link_to clients_path  do %>
          <div class="pl-5 mt-3 border-bottom">
            <p>
              See all the clients
            </p>
          </div>
        <% end %>

      </div>
    </div>

    <div class="main d-flex justify-content-center align-items-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/home.html.erb
<h1>Welcome!!</h1>